name: Java CI with Gradle

on: 
  push:

jobs: 
  get-version: 
    uses: shiipou/github-actions/.github/workflows/get-version.yml@main
    with: 
      release-branches: '^(main)$'
      
  build:
    name: Spring build
    runs-on: ubuntu-latest
    needs:
      - get-version
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
  
    - name: Build with Gradle Wrapper
      run: ./gradlew bootjar

  dependency-submission:

        runs-on: ubuntu-latest
        permissions:
          contents: write

        steps:
          - uses: actions/checkout@v4
          - name: Set up JDK 17
            uses: actions/setup-java@v4
            with:
              java-version: '17'
              distribution: 'temurin'
